### ISSUE TITLE
Does it support custom tool bar button functions?

### ISSUE THREAD

**Issue by Edward-Chen-CN** [evocount/ember-tui-editor#420]
Very nice component. Maybe I am missing something, but does it support adding custom tool bar buttons can trigger action function? If so can you please provide a simple example? Thanks

**Comment by ttill** [comment]
I guess you mean something like shown [here](https://nhn.github.io/tui.editor/latest/tutorial-example19-customizing-toolbar-buttons)? This is currently not possible directly, because the editor object is not exposed. But you could subclass the component. I would be open to and happy about contributions enabling this without having to subclass the component.

**Comment by miguelcobain** [comment]
You can accomplish this in two ways.

## Using `@toolbarItems`

in the template
```hbs
<TuiEditor
  @value={{this.value}}
  @onChange={{fn (mut this.value)}}
  @toolbarItems={{this.toolbarItems}}/>
```

and in the controller
```js
toolbarItems = [
  ['heading', 'bold', 'italic', 'strike'],
  ['hr', 'quote'],
  ['ul', 'ol', 'task', 'indent', 'outdent'],
  ['table', 'image', 'link'],
  ['code', 'codeblock'],
  // Using Option: Customize the last button
  [{
    el: createLastButton(),
    command: 'bold',
    tooltip: 'Custom Bold'
  }]
];

function createLastButton() {
  // ...
```

## Using `@onInit`

Since v3, there is a new action called `@onInit`. This action is called when the editor is initialized, and provides the editor instance as an argument. This allows you to make more advanced operations with it, including adding new toolbar buttons.

in the template
```hbs
<TuiEditor
  @value={{this.value}}
  @onChange={{fn (mut this.value)}}
  @onInit={{this.onEditorInit}}/>
```

and in the controller
```js
@action
onEditorInit(editor) {
  editor.insertToolbarItem({ groupIndex: 0, itemIndex: 0 }, {
    name: 'myItem',
    tooltip: 'Custom Button',
    command: 'bold',
    text: '@',
    className: 'toastui-editor-toolbar-icons first',
    style: { backgroundImage: 'none' }
  });
}
```

Both of these options map very nicely to the example in TUI editor docs: https://nhn.github.io/tui.editor/latest/tutorial-example15-customizing-toolbar-buttons

Please reopen if still an issue.
