### ISSUE TITLE
Integration and acceptance testing 

### ISSUE THREAD

**Issue by jelhan** [evocount/ember-tui-editor#477]
Thanks a lot for this great component. It works like a charm. I only struggled with testing. Tried to use `fillIn` helper from `@ember/testing`. But the input is not reflected in tui.editor and the `onChange` event is not fired. I tried to dispatch some events manually but wasn't able to figure out correct events. Did someone succeeded?

**Comment by miguelcobain** [comment]
@jelhan I released a new `3.0.2` version which adds a test helper that people can import in their integration tests.

So, in your tests you would import it as:
```js
import { fillInEditor } from 'ember-tui-editor/test-support/helpers';
```

and then use it as

```js
await render(hbs`
  <TuiEditor data-test-editor @onChange={{this.onChangeHandler}}/>
`);

await fillInEditor('[data-test-editor]', 'foo');
```

Here is the example test I added: https://github.com/evocount/ember-tui-editor/blob/master/tests/integration/components/tui-editor-test.js

And, if you're curious, here is how the helper is implemented: https://github.com/evocount/ember-tui-editor/blob/master/addon-test-support/helpers.js

I also updated the editor to the latest version, which I think fixed some issues around events. So that might have helped as well.

Please let me know if this works for you.
Would love to get this documented somehow in the readme as well.

**Comment by jelhan** [comment]
Thanks a lot for providing the quick feedback. Actually the test helper does exactly the same what I tried in my project. Somehow it is not working in my acceptance test. Still trying to figure out why it is not working for my use case.

I have a growing list of integration tests, which are using the test helper successfully. Trying to close the gap between my complex use case and the passing tests. Will keep you posted.

But looking at the huge list of passing integration tests, which I have written, I can clearly confirm that the test helper does it job. At least one good thing from that debugging exercise. :see_no_evil:

**Comment by jelhan** [comment]
I finally nailed it down. The test helper is not working with `@editType="wysiwyg"`. Please see here for a failing test: https://github.com/jelhan/reproduce-ember-tui-editor-acceptance-testing-issue/commit/de2f1158fc3a8125a2b5dae05fcdb548e2f6d24f Do you have an idea how to approach that? Switching to markdown editor before entering text might be a solution. Do you see a better one? Happy to provide a PR.

**Comment by miguelcobain** [comment]
@jelhan I updated the helper to work on "wysiwyg" mode and added your failing test. Thank you for reporting again.
Turns out that we need to target a different selector for "wysiwyg" mode.

Can you please test version `3.0.3`?

**Comment by jelhan** [comment]
Thanks a lot. It is working like a charm.

**Comment by miguelcobain** [comment]
@jelhan it would be nice to have this mentioned in a section of the readme. 🙏
